// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_template/test/features/lessons/presentation/cubit/lessons_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i3;

import 'package:dio/dio.dart' as _i11;
import 'package:mobile_template/core/models/paginated_result.dart' as _i7;
import 'package:mobile_template/core/utils/request_result.dart' as _i2;
import 'package:mobile_template/features/downloads/data/services/encrypted_download_service.dart'
    as _i9;
import 'package:mobile_template/features/downloads/data/services/offline_crypto.dart'
    as _i4;
import 'package:mobile_template/features/downloads/domain/entities/downloaded_lesson_info.dart'
    as _i12;
import 'package:mobile_template/features/lessons/domain/entities/lesson.dart'
    as _i8;
import 'package:mobile_template/features/lessons/domain/repositories/lessons_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRequestResult_0<T> extends _i1.SmartFake
    implements _i2.RequestResult<T> {
  _FakeRequestResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_1 extends _i1.SmartFake implements _i3.Directory {
  _FakeDirectory_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfflinePlaybackSource_2 extends _i1.SmartFake
    implements _i4.OfflinePlaybackSource {
  _FakeOfflinePlaybackSource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LessonsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLessonsRepository extends _i1.Mock implements _i5.LessonsRepository {
  @override
  _i6.Future<_i2.RequestResult<_i7.PaginatedResult<_i8.Lesson>>> getLessons(
    String? chapterId, {
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLessons,
              [chapterId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i6.Future<
                  _i2.RequestResult<_i7.PaginatedResult<_i8.Lesson>>
                >.value(
                  _FakeRequestResult_0<_i7.PaginatedResult<_i8.Lesson>>(
                    this,
                    Invocation.method(
                      #getLessons,
                      [chapterId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<
                  _i2.RequestResult<_i7.PaginatedResult<_i8.Lesson>>
                >.value(
                  _FakeRequestResult_0<_i7.PaginatedResult<_i8.Lesson>>(
                    this,
                    Invocation.method(
                      #getLessons,
                      [chapterId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i6.Future<_i2.RequestResult<_i7.PaginatedResult<_i8.Lesson>>>);

  @override
  _i6.Future<void> saveProgress(
    String? lessonId,
    int? positionSeconds,
    bool? isCompleted,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgress, [
              lessonId,
              positionSeconds,
              isCompleted,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.RequestResult<T>> execute<T, TM>(
    _i6.FutureOr<TM> Function()? apiRequest, {
    _i6.FutureOr<T> Function(TM)? converter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [apiRequest], {#converter: converter}),
            returnValue: _i6.Future<_i2.RequestResult<T>>.value(
              _FakeRequestResult_0<T>(
                this,
                Invocation.method(
                  #execute,
                  [apiRequest],
                  {#converter: converter},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.RequestResult<T>>.value(
              _FakeRequestResult_0<T>(
                this,
                Invocation.method(
                  #execute,
                  [apiRequest],
                  {#converter: converter},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.RequestResult<T>>);

  @override
  _i2.RequestResult<T> executeSync<T, TM>(
    TM Function()? request, {
    T Function(TM)? converter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeSync, [request], {#converter: converter}),
            returnValue: _FakeRequestResult_0<T>(
              this,
              Invocation.method(
                #executeSync,
                [request],
                {#converter: converter},
              ),
            ),
            returnValueForMissingStub: _FakeRequestResult_0<T>(
              this,
              Invocation.method(
                #executeSync,
                [request],
                {#converter: converter},
              ),
            ),
          )
          as _i2.RequestResult<T>);
}

/// A class which mocks [EncryptedDownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptedDownloadService extends _i1.Mock
    implements _i9.EncryptedDownloadService {
  @override
  List<String> get expiredOnLastReconcile =>
      (super.noSuchMethod(
            Invocation.getter(#expiredOnLastReconcile),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i6.Future<_i9.DownloadOutcome> downloadLesson({
    required String? lessonId,
    required String? videoUrl,
    required String? studentId,
    required String? deviceUuid,
    required _i6.Future<String> Function()? accessToken,
    required void Function(double)? onProgress,
    String? title = '',
    int? durationSeconds = 0,
    String? thumbnailUrl,
    void Function(int, int)? onBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadLesson, [], {
              #lessonId: lessonId,
              #videoUrl: videoUrl,
              #studentId: studentId,
              #deviceUuid: deviceUuid,
              #accessToken: accessToken,
              #onProgress: onProgress,
              #title: title,
              #durationSeconds: durationSeconds,
              #thumbnailUrl: thumbnailUrl,
              #onBytes: onBytes,
            }),
            returnValue: _i6.Future<_i9.DownloadOutcome>.value(
              _i9.DownloadOutcome.completed,
            ),
            returnValueForMissingStub: _i6.Future<_i9.DownloadOutcome>.value(
              _i9.DownloadOutcome.completed,
            ),
          )
          as _i6.Future<_i9.DownloadOutcome>);

  @override
  _i6.Future<_i3.Directory> lessonDirectory(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#lessonDirectory, [lessonId]),
            returnValue: _i6.Future<_i3.Directory>.value(
              _FakeDirectory_1(
                this,
                Invocation.method(#lessonDirectory, [lessonId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.Directory>.value(
              _FakeDirectory_1(
                this,
                Invocation.method(#lessonDirectory, [lessonId]),
              ),
            ),
          )
          as _i6.Future<_i3.Directory>);

  @override
  _i6.Future<void> beginDownload(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#beginDownload, [lessonId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> discardPartial(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#discardPartial, [lessonId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> resolveDownloadUrl({
    required String? videoUrl,
    required _i6.Future<String> Function()? accessToken,
    required String? deviceUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDownloadUrl, [], {
              #videoUrl: videoUrl,
              #accessToken: accessToken,
              #deviceUuid: deviceUuid,
            }),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#resolveDownloadUrl, [], {
                  #videoUrl: videoUrl,
                  #accessToken: accessToken,
                  #deviceUuid: deviceUuid,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#resolveDownloadUrl, [], {
                  #videoUrl: videoUrl,
                  #accessToken: accessToken,
                  #deviceUuid: deviceUuid,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> finalizeTransferredFile({
    required String? lessonId,
    required int? expectedTotal,
    required String? studentId,
    required String? deviceUuid,
    required _i6.Future<String> Function()? accessToken,
    required void Function(double)? onProgress,
    String? title = '',
    int? durationSeconds = 0,
    String? thumbnailUrl,
    _i11.Dio? dio,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeTransferredFile, [], {
              #lessonId: lessonId,
              #expectedTotal: expectedTotal,
              #studentId: studentId,
              #deviceUuid: deviceUuid,
              #accessToken: accessToken,
              #onProgress: onProgress,
              #title: title,
              #durationSeconds: durationSeconds,
              #thumbnailUrl: thumbnailUrl,
              #dio: dio,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool isActive(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#isActive, [lessonId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void pause(String? lessonId) => super.noSuchMethod(
    Invocation.method(#pause, [lessonId]),
    returnValueForMissingStub: null,
  );

  @override
  void cancel(String? lessonId) => super.noSuchMethod(
    Invocation.method(#cancel, [lessonId]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i4.OfflinePlaybackSource> prepareOfflinePlayback({
    required String? lessonId,
    required String? studentId,
    required String? deviceUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#prepareOfflinePlayback, [], {
              #lessonId: lessonId,
              #studentId: studentId,
              #deviceUuid: deviceUuid,
            }),
            returnValue: _i6.Future<_i4.OfflinePlaybackSource>.value(
              _FakeOfflinePlaybackSource_2(
                this,
                Invocation.method(#prepareOfflinePlayback, [], {
                  #lessonId: lessonId,
                  #studentId: studentId,
                  #deviceUuid: deviceUuid,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.OfflinePlaybackSource>.value(
                  _FakeOfflinePlaybackSource_2(
                    this,
                    Invocation.method(#prepareOfflinePlayback, [], {
                      #lessonId: lessonId,
                      #studentId: studentId,
                      #deviceUuid: deviceUuid,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.OfflinePlaybackSource>);

  @override
  _i6.Future<List<String>> purgeExpired() =>
      (super.noSuchMethod(
            Invocation.method(#purgeExpired, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> markValidated(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#markValidated, [lessonId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markDamaged(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#markDamaged, [lessonId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> reconcileOnStartup({bool Function(String)? isTracked}) =>
      (super.noSuchMethod(
            Invocation.method(#reconcileOnStartup, [], {#isTracked: isTracked}),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  bool isPastOfflineLifetime(Map<dynamic, dynamic>? meta) =>
      (super.noSuchMethod(
            Invocation.method(#isPastOfflineLifetime, [meta]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> purgeEverything() =>
      (super.noSuchMethod(
            Invocation.method(#purgeEverything, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteLesson(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLesson, [lessonId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  bool isDownloaded(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#isDownloaded, [lessonId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int? chunkCount(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#chunkCount, [lessonId]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  int totalBytesUsed() =>
      (super.noSuchMethod(
            Invocation.method(#totalBytesUsed, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i12.DownloadedLessonInfo> getDownloadedLessons() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedLessons, []),
            returnValue: <_i12.DownloadedLessonInfo>[],
            returnValueForMissingStub: <_i12.DownloadedLessonInfo>[],
          )
          as List<_i12.DownloadedLessonInfo>);
}
