// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_template/test/features/lessons/presentation/cubit/lessons_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile_template/core/models/paginated_result.dart' as _i5;
import 'package:mobile_template/core/utils/request_result.dart' as _i2;
import 'package:mobile_template/features/downloads/data/services/encrypted_download_service.dart'
    as _i7;
import 'package:mobile_template/features/downloads/domain/entities/downloaded_lesson_info.dart'
    as _i9;
import 'package:mobile_template/features/lessons/domain/entities/lesson.dart'
    as _i6;
import 'package:mobile_template/features/lessons/domain/repositories/lessons_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRequestResult_0<T> extends _i1.SmartFake
    implements _i2.RequestResult<T> {
  _FakeRequestResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LessonsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLessonsRepository extends _i1.Mock implements _i3.LessonsRepository {
  @override
  _i4.Future<_i2.RequestResult<_i5.PaginatedResult<_i6.Lesson>>> getLessons(
    String? chapterId, {
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLessons,
              [chapterId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<
                  _i2.RequestResult<_i5.PaginatedResult<_i6.Lesson>>
                >.value(
                  _FakeRequestResult_0<_i5.PaginatedResult<_i6.Lesson>>(
                    this,
                    Invocation.method(
                      #getLessons,
                      [chapterId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.RequestResult<_i5.PaginatedResult<_i6.Lesson>>
                >.value(
                  _FakeRequestResult_0<_i5.PaginatedResult<_i6.Lesson>>(
                    this,
                    Invocation.method(
                      #getLessons,
                      [chapterId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.RequestResult<_i5.PaginatedResult<_i6.Lesson>>>);

  @override
  _i4.Future<void> saveProgress(
    String? lessonId,
    int? positionSeconds,
    bool? isCompleted,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgress, [
              lessonId,
              positionSeconds,
              isCompleted,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.RequestResult<T>> execute<T, TM>(
    _i4.FutureOr<TM> Function()? apiRequest, {
    _i4.FutureOr<T> Function(TM)? converter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [apiRequest], {#converter: converter}),
            returnValue: _i4.Future<_i2.RequestResult<T>>.value(
              _FakeRequestResult_0<T>(
                this,
                Invocation.method(
                  #execute,
                  [apiRequest],
                  {#converter: converter},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.RequestResult<T>>.value(
              _FakeRequestResult_0<T>(
                this,
                Invocation.method(
                  #execute,
                  [apiRequest],
                  {#converter: converter},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.RequestResult<T>>);

  @override
  _i2.RequestResult<T> executeSync<T, TM>(
    TM Function()? request, {
    T Function(TM)? converter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeSync, [request], {#converter: converter}),
            returnValue: _FakeRequestResult_0<T>(
              this,
              Invocation.method(
                #executeSync,
                [request],
                {#converter: converter},
              ),
            ),
            returnValueForMissingStub: _FakeRequestResult_0<T>(
              this,
              Invocation.method(
                #executeSync,
                [request],
                {#converter: converter},
              ),
            ),
          )
          as _i2.RequestResult<T>);
}

/// A class which mocks [EncryptedDownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptedDownloadService extends _i1.Mock
    implements _i7.EncryptedDownloadService {
  @override
  _i4.Future<_i7.DownloadOutcome> downloadLesson({
    required String? lessonId,
    required String? videoUrl,
    required String? studentId,
    required String? deviceUuid,
    required _i4.Future<String> Function()? accessToken,
    required void Function(double)? onProgress,
    String? title = '',
    int? durationSeconds = 0,
    String? thumbnailUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadLesson, [], {
              #lessonId: lessonId,
              #videoUrl: videoUrl,
              #studentId: studentId,
              #deviceUuid: deviceUuid,
              #accessToken: accessToken,
              #onProgress: onProgress,
              #title: title,
              #durationSeconds: durationSeconds,
              #thumbnailUrl: thumbnailUrl,
            }),
            returnValue: _i4.Future<_i7.DownloadOutcome>.value(
              _i7.DownloadOutcome.completed,
            ),
            returnValueForMissingStub: _i4.Future<_i7.DownloadOutcome>.value(
              _i7.DownloadOutcome.completed,
            ),
          )
          as _i4.Future<_i7.DownloadOutcome>);

  @override
  bool isActive(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#isActive, [lessonId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void pause(String? lessonId) => super.noSuchMethod(
    Invocation.method(#pause, [lessonId]),
    returnValueForMissingStub: null,
  );

  @override
  void cancel(String? lessonId) => super.noSuchMethod(
    Invocation.method(#cancel, [lessonId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<String> getOfflineVideoPath({
    required String? lessonId,
    required String? studentId,
    required String? deviceUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOfflineVideoPath, [], {
              #lessonId: lessonId,
              #studentId: studentId,
              #deviceUuid: deviceUuid,
            }),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getOfflineVideoPath, [], {
                  #lessonId: lessonId,
                  #studentId: studentId,
                  #deviceUuid: deviceUuid,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getOfflineVideoPath, [], {
                  #lessonId: lessonId,
                  #studentId: studentId,
                  #deviceUuid: deviceUuid,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> markValidated(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#markValidated, [lessonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markDamaged(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#markDamaged, [lessonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> reconcileOnStartup() =>
      (super.noSuchMethod(
            Invocation.method(#reconcileOnStartup, []),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> deleteLesson(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLesson, [lessonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> clearTempFile(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#clearTempFile, [lessonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isDownloaded(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#isDownloaded, [lessonId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int? chunkCount(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#chunkCount, [lessonId]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  int totalBytesUsed() =>
      (super.noSuchMethod(
            Invocation.method(#totalBytesUsed, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i9.DownloadedLessonInfo> getDownloadedLessons() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedLessons, []),
            returnValue: <_i9.DownloadedLessonInfo>[],
            returnValueForMissingStub: <_i9.DownloadedLessonInfo>[],
          )
          as List<_i9.DownloadedLessonInfo>);
}
