// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_template/test/features/example_feature/example_feature_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile_template/core/entities/pagination_list.dart' as _i5;
import 'package:mobile_template/core/utils/request_result.dart' as _i2;
import 'package:mobile_template/features/example_feature/domain/entities/example_item.dart'
    as _i6;
import 'package:mobile_template/features/example_feature/domain/use_cases/get_example_items_use_case.dart'
    as _i3;
import 'package:mobile_template/features/example_feature/domain/use_cases/like_example_item_use_case.dart'
    as _i7;
import 'package:mobile_template/features/example_feature/domain/use_cases/unlike_example_item_use_case.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRequestResult_0<T> extends _i1.SmartFake
    implements _i2.RequestResult<T> {
  _FakeRequestResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetExampleItemsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExampleItemsUseCase extends _i1.Mock
    implements _i3.GetExampleItemsUseCase {
  @override
  _i4.Future<_i2.RequestResult<_i5.PaginationList<_i6.ExampleItem>>> call(
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [page]),
            returnValue:
                _i4.Future<
                  _i2.RequestResult<_i5.PaginationList<_i6.ExampleItem>>
                >.value(
                  _FakeRequestResult_0<_i5.PaginationList<_i6.ExampleItem>>(
                    this,
                    Invocation.method(#call, [page]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.RequestResult<_i5.PaginationList<_i6.ExampleItem>>
                >.value(
                  _FakeRequestResult_0<_i5.PaginationList<_i6.ExampleItem>>(
                    this,
                    Invocation.method(#call, [page]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.RequestResult<_i5.PaginationList<_i6.ExampleItem>>
          >);
}

/// A class which mocks [LikeExampleItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLikeExampleItemUseCase extends _i1.Mock
    implements _i7.LikeExampleItemUseCase {
  @override
  _i4.Future<_i2.RequestResult<void>> call(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [itemId]),
            returnValue: _i4.Future<_i2.RequestResult<void>>.value(
              _FakeRequestResult_0<void>(
                this,
                Invocation.method(#call, [itemId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.RequestResult<void>>.value(
                  _FakeRequestResult_0<void>(
                    this,
                    Invocation.method(#call, [itemId]),
                  ),
                ),
          )
          as _i4.Future<_i2.RequestResult<void>>);
}

/// A class which mocks [UnlikeExampleItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnlikeExampleItemUseCase extends _i1.Mock
    implements _i8.UnlikeExampleItemUseCase {
  @override
  _i4.Future<_i2.RequestResult<void>> call(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [itemId]),
            returnValue: _i4.Future<_i2.RequestResult<void>>.value(
              _FakeRequestResult_0<void>(
                this,
                Invocation.method(#call, [itemId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.RequestResult<void>>.value(
                  _FakeRequestResult_0<void>(
                    this,
                    Invocation.method(#call, [itemId]),
                  ),
                ),
          )
          as _i4.Future<_i2.RequestResult<void>>);
}
