// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_template/test/features/example_feature/example_feature_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mobile_template/features/example_feature/data/data_sources/example_feature_remote_data_source.dart'
    as _i4;
import 'package:mobile_template/features/example_feature/data/models/example_item_model.dart'
    as _i3;
import 'package:mobile_template/features/example_feature/data/models/example_items_pagination_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExampleItemsPaginationModel_0 extends _i1.SmartFake
    implements _i2.ExampleItemsPaginationModel {
  _FakeExampleItemsPaginationModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExampleItemModel_1 extends _i1.SmartFake
    implements _i3.ExampleItemModel {
  _FakeExampleItemModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExampleFeatureRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleFeatureRemoteDataSource extends _i1.Mock
    implements _i4.ExampleFeatureRemoteDataSource {
  @override
  _i5.Future<_i2.ExampleItemsPaginationModel> getExampleItems(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#getExampleItems, [page]),
            returnValue: _i5.Future<_i2.ExampleItemsPaginationModel>.value(
              _FakeExampleItemsPaginationModel_0(
                this,
                Invocation.method(#getExampleItems, [page]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ExampleItemsPaginationModel>.value(
                  _FakeExampleItemsPaginationModel_0(
                    this,
                    Invocation.method(#getExampleItems, [page]),
                  ),
                ),
          )
          as _i5.Future<_i2.ExampleItemsPaginationModel>);

  @override
  _i5.Future<_i3.ExampleItemModel> getExampleItemById(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getExampleItemById, [itemId]),
            returnValue: _i5.Future<_i3.ExampleItemModel>.value(
              _FakeExampleItemModel_1(
                this,
                Invocation.method(#getExampleItemById, [itemId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ExampleItemModel>.value(
              _FakeExampleItemModel_1(
                this,
                Invocation.method(#getExampleItemById, [itemId]),
              ),
            ),
          )
          as _i5.Future<_i3.ExampleItemModel>);

  @override
  _i5.Future<void> likeExampleItem(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#likeExampleItem, [itemId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unlikeExampleItem(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikeExampleItem, [itemId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
