import 'package:hive_ce/hive.dart';

import '../features/downloads/data/models/download_record.dart';

part 'hive_adapters.g.dart';

/// Every Hive TypeAdapter the app uses, generated by hive_ce_generator.
///
/// Type ids are pinned in `hive_adapters.g.yaml` (generated, checked in) so
/// they stay stable across releases — never edit that file by hand, and only
/// ever APPEND to this list.
@GenerateAdapters([AdapterSpec<DownloadRecordStatus>(), AdapterSpec<DownloadRecord>()])
// ignore: unused_element
void _() {}
